name: "Lua obfuscator"

on:
  workflow_call:
    inputs:
      dirs:
        type: string
        required: true
        description: "JSON Array of the dirs that should be obfuscated"

      input-branch:
        type: string
        description: "Which branch to clone and obfuscate"
        default: ${{ github.event.repository.default_branch }}
        required: false

      output-branch:
        type: string
        description: "Which branch to force-push the obfuscated code to"
        default: "obfuscated"
        required: false

      preset:
        type: choice
        description: "Which obfuscation preset to use"
        options:
          - Minify
          - Vm
          - Weak
          - Medium
          - Strong
        default: Strong
        required: false

jobs:
  obfuscate:
    name: "Perform Obfuscation"
    runs-on: ubuntu-18.04

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: project
          ref: ${{ inputs.input-branch }}

      - name: "Check out the obfuscator"
        uses: actions/checkout@v2
        with:
          repository: levno-710/Prometheus
          path: prometheus

      - name: "Set up Lua"
        run: sudo apt install -y lua5.1

      - name: "Save the dirs config"
        run: echo -e '${{ inputs.dirs }}' > "$GITHUB_WORKSPACE/dirs.json" && cat "$GITHUB_WORKSPACE/dirs.json"

      - name: "Run obfuscator"
        run: |
          cd "$GITHUB_WORKSPACE/project";
          readarray -t dirs < <(jq -rc '.[]' "$GITHUB_WORKSPACE/dirs.json");

          for dir in "${dirs[@]}"; do \
              find "./$dir" -name "*.lua" -exec sh -c 'lua5.1 ../prometheus/cli.lua --preset ${{ inputs.preset }} --out "{}" "{}" &' \;
          done;

          wait $(jobs -p);

      - name: "Remove .github"
        run: |
          cd "$GITHUB_WORKSPACE/project"
          rm -rfv .github

      - name: "Create VERSION file"
        run: |
          cd "$GITHUB_WORKSPACE/project"
          echo -e "${{ github.sha }}" > VERSION

      - name: Push to lua branch
        run: |
          cd "$GITHUB_WORKSPACE/project"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Obfuscation run for: $(cat VERSION)"
          git push -f origin "HEAD:${{ inputs.output-branch }}"
